### ISSUE TITLE
Module 2-create your own functions - text columns

### ISSUE THREAD

**Issue by catalicu** [sib-swiss/first-steps-with-python-training#1]
Your tutorials are fantastic! minor format issues: the multiple column format in some pages (ex: module 2 in python training) collapse the text and making it unreadable. Hope to see it fixed to complete the tutorial! thank you.

**Comment by WandrilleD** [comment]
Dear @catalicu; sorry for answering you so late. I discovered I am not notified when someone creates an issue...
Anyway, the graphical problem you describe only exists in the rendering of the jupyter notebook on github.com (and I am not sure why...).
If you clone the repository and open the notebook on your local machine (using jupyter notebook or jupyter lab) you should not have this issue.
Let us know if this works for you.
Best, Wandrille
