### ISSUE TITLE
Notebook 1: move tuple info to after list 

### ISSUE THREAD

**Issue by WandrilleD** [sib-swiss/first-steps-with-python-training#7]
the idea is to separate tuple and list information.
we would focus first on lists,
and then after that we mention tuple as a form of list which is immutable. 
hopefully, this would reduce the mental load of trainees so they can focus on one concept at a time.

**Comment by robinengler** [comment]
Done in commit 50d1dd3feb6ebaa8ee62aaf1d8d1827ebab85f82
